### ISSUE TITLE
npm install --loglevel error

### ISSUE THREAD

**Issue by jet10000** [GarrettCannon/snowpack-svelte-ts-tw#1]
```
  node v15.2.0
  npm  v7.0.10

npx create-snowpack-app snow-svelte-ts-tw-app --template snowpack-svelte-ts-tw
```  

shortMessage: 'Command failed with exit code 1: npm install --loglevel error',

**Comment by GarrettCannon** [comment]
I tested with node 15 and npm 7 and I'm getting the error as well. I'll take a look into it. Meanwhile, I know it works with earlier versions of node and npm, so rolling back at least for the init should be a valid work around.

**Comment by jet10000** [comment]
```
git clone https://github.com/GarrettCannon/snowpack-svelte-ts-tw.git snow-svelte-tw-app
cd snow-svelte-tw-app
rm yarn.lock
pnpm install
pnpm start
```

It's worked.
