### ISSUE TITLE
works for github pages?

### ISSUE THREAD

**Issue by markfirmware** [GarrettCannon/snowpack-svelte-ts-tw#2]
I am interested to see if this works for github pages. Is this github template the only starting point or can I use npx create-snowpack-app? Thanks, Mark.

**Comment by GarrettCannon** [comment]
I haven't worked with Github pages enough to answer, but if you try it, let me know what happens!

**Comment by markfirmware** [comment]
@GarrettCannon my more specific and immediate question is whether I can use npx create-snowpack-app instead of instantiating the github template repo. In that case, what would be the argument to the --template option?

**Comment by jzillmann** [comment]
@markfirmware Not sure if that answers your question, but i had to do the following tweaks to make my github deployment work:
- Add empty `docs/.nojekyll` to fix references to `__snowpack__` and `_dist_`
- Make links in index.html relative
- Fix other references by setting baseUrl and webModulesUrl in `snowpack.config.js` See https://www.snowpack.dev/#config.buildoptions

**Comment by markfirmware** [comment]
> @GarrettCannon my more specific and immediate question is whether I can use npx create-snowpack-app instead of instantiating the github template repo. In that case, what would be the argument to the --template option?

The answer is

    npx create-snowpack-app --template snowpack-svelte-ts-tw new-dir

> @markfirmware Not sure if that answers your question, but i had to do the following tweaks to make my github deployment work:
> 
>     * Add empty `docs/.nojekyll` to fix references to `__snowpack__` and `_dist_`
> 
>     * Make links in index.html relative
> 
>     * Fix other references by setting baseUrl and webModulesUrl in `snowpack.config.js` See https://www.snowpack.dev/#config.buildoptions

**Comment by markfirmware** [comment]
> @markfirmware Not sure if that answers your question, but i had to do the following tweaks to make my github deployment work:
> 
>     * Add empty `docs/.nojekyll` to fix references to `__snowpack__` and `_dist_`
> 
>     * Make links in index.html relative
> 
>     * Fix other references by setting baseUrl and webModulesUrl in `snowpack.config.js` See https://www.snowpack.dev/#config.buildoptions

Thanks. The webModulesUrl is new to me. Related effort: https://github.com/snowpackjs/snowpack/pull/1517#discussion_r523836449
