### ISSUE TITLE
While booting snowpack up, it takes 10-20 seconds until it will run in the browser

### ISSUE THREAD

**Issue by samuelandert** [GarrettCannon/snowpack-svelte-ts-tw#3]
Any idea where this might be coming from?

**Comment by GarrettCannon** [comment]
I've noticed this is pretty normal for the majority of Snowpack projects I've worked on, as it needs to generate the esm files from your node_modules. After the initial build it should be faster after that, although adding new npm packages will probably case a delay on the next run on install for when Snowpack builds the new packages. 

Its *possible* that some of the delay is from the initial Tailwindcss build, but on non-Snowpack projects the Tailwind compile is pretty much instantaneous, so I doubt thats it.

I would try some other Snowpack templates and see if you notice the same behavior.

**Comment by samuelandert** [comment]
I was playing with different svelte snowpack templates and setups and it usually seems to be instanteous. Only the moment I add tailwind to the game manually or with your template booting takes this Long. So far I don't unterstand enough to look under the hood, why it is behaving like this.

**Comment by GarrettCannon** [comment]
@samuelandert I pushed a new version of this template that uses Snowpack to do the Tailwind build rather than Svelte-Preprocess. In my experience its greatly speeds up start up time, hopefully it works for you too. Let me know!

**Comment by samuelandert** [comment]
Nice, yes this indeed fixed it! 
I found another issue, as it seems to ignore now the @apply option inside the style tag of svelte files.

**Comment by GarrettCannon** [comment]
I pushed up another version to fix that. I had to re-enable postcss in svelte-preprocess. So Snowpack still handles tailwind, but for @apply rules and etc svelte preprocess should handle it now. Make sure you have version 1.2.2 and try it now!

**Comment by samuelandert** [comment]
Perfect!
