### ISSUE TITLE
github template vs csa template

### ISSUE THREAD

**Issue by markfirmware** [GarrettCannon/snowpack-svelte-ts-tw#6]
What is the difference between

1. instantiating this template repo in github
2. using npx csa followed by push new repo to github

If I instantiate the repo, why does the readme tell me to use npx csa?

**Comment by GarrettCannon** [comment]
It's just two alternative ways to set up the template, use whichever way you like better!

**Comment by markfirmware** [comment]
Good enough, thanks.
