### ISSUE TITLE
Type checking

### ISSUE THREAD

**Issue by davemccrea** [GarrettCannon/snowpack-svelte-ts-tw#8]
Thanks for throwing this template together!

Do you know is it possible to get type checking when running `yarn run start` or `yarn run build`? I have tried the following with no luck:

```javascript
module.exports = {
	...
	plugins: [
		...
		["@snowpack/plugin-typescript", { tsc: "tsc" }],
	],
};
```

And using `@snowpack/plugin-build-script`, but I would think using tsc would be the better option:

```javascript
module.exports = {
	...
	plugins: [
                 ...
		[
			"@snowpack/plugin-build-script",
			{ cmd: 'svelte-check', watch: '$1 --watch', output: 'stream' },
		],
	],
};
```

**Comment by GarrettCannon** [comment]
Currently the best option is probably to use something like https://www.npmjs.com/package/npm-run-all to run the `yarn start` and `yarn ts-check` at the same time. You do currently get type checking on .ts files but on .svelte files you will have to use svelte-check. It might actually be a useful plugin i might look into writing to integrate svelte-check with Snowpack properly. 
Hopefully Svelte continues to improve their typescript support to make it a more integrated process.
